### ISSUE TITLE
TC Flag not set for Externalname kind service when the payload is large

### ISSUE THREAD

**Issue by TheRealGoku** [coredns/coredns#4684]
As explained in this article
https://easoncao.com/coredns-resolution-truncation-issue-on-kubernetes-kube-dns/

Ideal behavior - the response should contain not just cname but also all ip's that belongs to the cname. If the server(coredns) is not able to sandwich all the ip's due to payload limit of 512, it should send partial payload and with Truncate flag set, once this partial truncate response was received by the client, the client will use tcp as a mode to send same dns query again,

Since coredns failed to set the truncate flag and since the "A" authoritative flag was set, clients neither upgrading the request to tcp nor utilizing recursive strategy to send follow up "A" query to cname. The reason behind setting "A" could be acceptable due to the fact that coredns has dual responsibility (as a Authoritative domain for local kubernetes related services, as a recursive resolver for external internet domains)

The only concern here is a coredns just responding with cname without even setting truncate flag.

**Tested Potential workarounds:**

1. Forcefully make the clients(pods) to use just tcp mode when interacting with coredns pods. This could be simply configured with the help of use-vc flag like below
```
  template:
    metadata:
      labels:
        app: customer-dns
    spec:
      dnsConfig:
        options:
          - name: use-vc
      containers:
        - name: customer-dns
          image: nginx:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
```
 
2. As a win win situation, the customer could use nodelocaldns cache, as the communication from nodelocaldns cache to the coredns pod will be by default tcp, and the communication between pod to the nodelocaldns pod can either be tcp or udp.

As per my testing, implementing nodelocaldns cache solved the issue as now the issue is being masked since nodelocalcache dns implementation didnt act in that unexpected way.

**Comment by chrisohaver** [comment]
I'm pretty certain this was fixed by https://github.com/miekg/dns/pull/1171, which is included in CoreDNS in the 1.8.0/1.8.1 timeframe.  The article referenced used CoreDNS 1.6.6, which did not have that fix.

**Comment by TheRealGoku** [comment]
Thanks @chrisohaver , I have recently tested this behavior in EKS 1.18 running CoreDNS-1.7.0. Will test this now on EKS 1.20 which should have CoreDNS 1.8.3. do you recall which exact version this got merged in?

**Comment by chrisohaver** [comment]
I just checked... it was released in miekg/dns 1.34, which was included in CoreDNS 1.8.0.

Thanks for testing!

**Comment by TheRealGoku** [comment]
I could confirm that its the same behavior for ExternalName in CoreDNS-1.8.3 on EKS 1.20, The issue still persist. I could also conclude that this issue is not happening for direct queries to a domain which has larger reply payload but only for ExternalName type service

**Environment**
Kubernetes version - EKS 1.20
CoreDns version - CoreDNS-1.8.3

**Steps:**

1. To make sure we have control of less and more dns payload , I have created a private hosted zone with entries like below and attached it to the same VPC of EKS cluster
![image](https://user-images.githubusercontent.com/80927054/121444547-a753ff80-c987-11eb-9e90-be12ed183a24.png)
![image](https://user-images.githubusercontent.com/80927054/121444576-b5a21b80-c987-11eb-9b41-e3db43441f03.png)


2. Now create a ExternalName type services referring above names, in real life scenario this could be elastically scaled redis cluster domains.
    kubectl apply -f lesspayload.yaml
    kubectl apply -f morepayload.yaml
    kubectl apply -f nginx-deployment.yaml

  File - lesspayload.yaml
  
  ```
  apiVersion: v1
  kind: Service
  metadata:
    name: lesspayload
    namespace: default
  spec:
    externalName: lesspayload.playwithtc.com
    type: ExternalName
  ```

  File - morepayload.yaml
  
  ```
  apiVersion: v1
  kind: Service
  metadata:
    name: morepayload
    namespace: default
  spec:
    externalName: morepayload.playwithtc.com
    type: ExternalName
  ```

  File - nginx-deployment.yaml
  ```
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-deployment
  spec:
    selector:
      matchLabels:
        app: nginx
    replicas: 1
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: nginx
            image: nginx:latest
            ports:
              - containerPort: 80
  ```
3. Verify that ExternalName service got created
```
$ kubectl get svc
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
kubernetes ClusterIP 10.100.0.1 <none> 443/TCP 36m
lesspayload ExternalName <none> lesspayload.playwithtc.com <none> 17m
morepayload ExternalName <none> morepayload.playwithtc.com <none> 17m
```

```
$ kubectl logs deployment/coredns -n kube-system
Found 2 pods, using pod/coredns-85cc4f6d5-zs64x
.:53
[INFO] plugin/reload: Running configuration MD5 = 47d57903c0f0ba4ee0626a17181e5d94
CoreDNS-1.8.3
linux/amd64, go1.13.15, 4293992b
```
4. Exec into the nginx pod and try curl with verbose

For - lesspayload.default.svc.cluster.local.
```
root@nginx-deployment-66b6959498-rxh4z:/#
root@nginx-deployment-66b6959498-rxh4z:/# curl -v lesspayload.default.svc.cluster.local.

//truncated
- Expire in 1 ms for 1 (transfer 0x5587a2e58fb0)
- Expire in 1 ms for 1 (transfer 0x5587a2e58fb0)
- Trying 10.0.5.24...
- TCP_NODELAY set
- Expire in 149998 ms for 3 (transfer 0x5587a2e58fb0)
- E

^C
```

For - curl -v morepayload.default.svc.cluster.local.

```
root@nginx-deployment-66b6959498-rxh4z:/# curl -v morepayload.default.svc.cluster.local.

//truncated
- Expire in 2 ms for 1 (transfer 0x557b79cdafb0)
- Expire in 1 ms for 1 (transfer 0x557b79cdafb0)
- Expire in 1 ms for 1 (transfer 0x557b79cdafb0)
- Could not resolve host: morepayload.default.svc.cluster.local.
- Expire in 2 ms for 1 (transfer 0x557b79cdafb0)
- Closing connection 0
  curl: (6) Could not resolve host: morepayload.default.svc.cluster.local
```

**Attachment:**
https://github.com/TheRealGoku/coredns-tc-behavior

1. coredns-behavior-non_working.pcap - This capture is taken in parallel on client pod side when the curl request "lesspayload.default.svc.cluster.local." and "morepayload.default.svc.cluster.local." are made

2. coredns-behavior-working.pcap - This capture is taken in parallel on client pod side when the curl request "lesspayload.playwithtc.com" and "morepayload.playwithtc.com" are made


As per the above two pcaps, its evident that only in ExternalName scenario with high payload the CoreDNS is not setting TC flag and sending just CNAME in response without any IP response

In other scenario(coredns-behavior-working.pcap) when querying the direct domain which has heavy payload, its setting the TC flag as expected thereby client is making connection over TCP.

**Comment by chrisohaver** [comment]
Looks like this is standard DNS behavior defined in RFCs.

https://datatracker.ietf.org/doc/html/rfc2181#section-9

```
9. The TC (truncated) header bit

   The TC bit should be set in responses only when an RRSet is required
   as a part of the response, but could not be included in its entirety.
   The TC bit should not be set merely because some extra information
   could have been included, but there was insufficient room.  This
   includes the results of additional section processing.  In such cases
   the entire RRSet that will not fit in the response should be omitted,
   and the reply sent as is, with the TC bit clear.  If the recipient of
   the reply needs the omitted data, it can construct a query for that
   data and send that separately.

   Where TC is set, the partial RRSet that would not completely fit may
   be left in the response.  When a DNS client receives a reply with TC
   set, it should ignore that response, and query again, using a
   mechanism, such as a TCP connection, that will permit larger replies.
```

**Comment by chrisohaver** [comment]
> Looks like this is standard DNS behavior defined in RFCs.
> https://datatracker.ietf.org/doc/html/rfc2181#section-9

Although - this may not apply to CNAMEs, since the "additional" records are in the _answer_ section - not the _additional_ section.

**Comment by chrisohaver** [comment]
> In other scenario(coredns-behavior-working.pcap) when querying the direct domain which has heavy payload, its setting the TC flag as expected thereby client is making connection over TCP.

Can you test this with just a CNAME to the domain?  K8s externalName is treated just as a CNAME, so the behavior is probably the same.  If so, we can decouple this behavior from the complexity of Kubernetes.

**Comment by chrisohaver** [comment]
I tested with a CNAME using _template_, and I got a partial truncated response `*`, so this may be something to do with how `backend_lookup.go` handles CNAMES?

`*` Actually - the partial response sometimes has the TC bit set, and sometimes doesn't, depending on length and content of the full set of records. Clearly a bug, possibly related to compression? But I don't think its the cause of the issue here.

**Comment by chrisohaver** [comment]
I did a test with a Kubernetes ExternalName Service and CoreDNS as the upstream server, and I got a partial response with TC bit set, as expected. I am testing with `dig`, with ` +noedns` (to not use edns buffer size option), and  `+ignore` (to show the initial reply, and not retry over TCP)

```
% kubectl get svc       
NAME         TYPE           CLUSTER-IP   EXTERNAL-IP    PORT(S)   AGE
kubernetes   ClusterIP      10.96.0.1    <none>         443/TCP   19d
test         ExternalName   <none>       cname.target   <none>    87s


% dig @localhost -p5399 test.default.svc.cluster.local. +noedns +ignore

; <<>> DiG 9.10.6 <<>> @localhost -p5399 test.default.svc.cluster.local. +noedns +ignore
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52577
;; flags: qr aa tc rd; QUERY: 1, ANSWER: 28, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;test.default.svc.cluster.local.	IN	A

;; ANSWER SECTION:
test.default.svc.cluster.local.	5 IN	CNAME	cname.target.
cname.target.		3600	IN	A	1.0.0.0
cname.target.		3600	IN	A	1.0.0.1
cname.target.		3600	IN	A	1.0.0.2
cname.target.		3600	IN	A	1.0.0.3
cname.target.		3600	IN	A	1.0.0.4
cname.target.		3600	IN	A	1.0.0.5
cname.target.		3600	IN	A	1.0.0.6
cname.target.		3600	IN	A	1.0.0.7
cname.target.		3600	IN	A	1.0.0.8
cname.target.		3600	IN	A	1.0.0.9
cname.target.		3600	IN	A	2.0.0.0
cname.target.		3600	IN	A	2.0.0.1
cname.target.		3600	IN	A	2.0.0.2
cname.target.		3600	IN	A	2.0.0.3
cname.target.		3600	IN	A	2.0.0.4
cname.target.		3600	IN	A	2.0.0.5
cname.target.		3600	IN	A	2.0.0.6
cname.target.		3600	IN	A	2.0.0.7
cname.target.		3600	IN	A	2.0.0.8
cname.target.		3600	IN	A	2.0.0.9
cname.target.		3600	IN	A	3.0.0.0
cname.target.		3600	IN	A	3.0.0.1
cname.target.		3600	IN	A	3.0.0.2
cname.target.		3600	IN	A	3.0.0.3
cname.target.		3600	IN	A	3.0.0.4
cname.target.		3600	IN	A	3.0.0.5
cname.target.		3600	IN	A	3.0.0.6

;; Query time: 0 msec
;; SERVER: ::1#5399(::1)
;; WHEN: Thu Jun 10 14:14:38 EDT 2021
;; MSG SIZE  rcvd: 506

```

@TheRealGoku, In your tests, how large is the untruncated response for `morepayload`?

**Comment by TheRealGoku** [comment]
@chrisohaver In the first pcap file (coredns-behavior-non_working.pcap) see the frame number 9 thats the response from coredns for client query "morepayload.default.svc.cluster.local." 

The payload size in response is 55 bytes and just has cname in it

![image](https://user-images.githubusercontent.com/80927054/121583791-9e673a80-ca28-11eb-80d3-f0aac0e9fa75.png)

In addition, I performed a different test as you mentioned. The scenario follows where no kubernetes is involved

**Path**
Client(192.168.91.124) <-----> CoreDNS Server binary(192.168.88.71) <----->Route53 private hosted zone

**In Route 53 hosted zone**
cnamelesspayload.dnstest.com   ----CNAME Type ----  lesspayload.dnstest.com
lesspayload.dnstest.com  ----A----  7 IP's

cnamemorepayload.dnstest.com  ----CNAME Type ----  morepayload.dnstest.com
morepayload.dnstest.com  ----A----  180 IP's (Abnormal) can reduce if needed.

In this case,
The client was able to resolve both cnamelesspayload.dnstest.com and cnamemorepayload.dnstest.com, following are the coredns log of this scenario

```
INFO] 127.0.0.1:57765 - 31313 "HINFO IN 606962588873579644.2402289036478892081. udp 56 false 512" NXDOMAIN qr,rd,ra 131 0.003131798s
[INFO] 192.168.91.124:36114 - 25268 "AAAA IN cnamelesspayload.dnstest.com. udp 46 false 512" NOERROR qr,rd,ra 209 0.003014999s
[INFO] 192.168.91.124:36114 - 39347 "A IN cnamelesspayload.dnstest.com. udp 46 false 512" NOERROR qr,rd,ra 345 0.004628205s
[INFO] 192.168.91.124:58716 - 38842 "AAAA IN cnamemorepayload.dnstest.com. udp 46 false 512" NOERROR qr,rd,ra 209 0.004357516s
[INFO] 192.168.91.124:58716 - 63155 "A IN cnamemorepayload.dnstest.com. udp 46 false 512" NOERROR qr,tc,rd,ra 111 0.766637403s
[INFO] 192.168.91.124:55384 - 63155 "A IN cnamemorepayload.dnstest.com. tcp 46 false 65535" NOERROR qr,rd,ra 7131 0.002337455s
[INFO] 192.168.91.124:55384 - 38842 "AAAA IN cnamemorepayload.dnstest.com. tcp 46 false 65535" NOERROR qr,aa,rd,ra 209 0.00003977s
[INFO] 192.168.91.124:57448 - 7029 "AAAA IN cnamemorepayload.dnstest.com. udp 46 false 512" NOERROR qr,aa,rd,ra 209 0.000081507s
[INFO] 192.168.91.124:57448 - 7291 "A IN cnamemorepayload.dnstest.com. udp 46 false 512" NOERROR qr,aa,tc,rd,ra 7131 0.000769713s
[INFO] 192.168.91.124:55386 - 7291 "A IN cnamemorepayload.dnstest.com. tcp 46 false 65535" NOERROR qr,aa,rd,ra 7131 0.000805356s
[INFO] 192.168.91.124:55386 - 7029 "AAAA IN cnamemorepayload.dnstest.com. tcp 46 false 65535" NOERROR qr,aa,rd,ra 209 0.000050166s
[INFO] 192.168.91.124:43375 - 43245 "AAAA IN cnamemorepayload.dnstest.com. udp 46 false 512" NOERROR qr,aa,rd,ra 209 0.000046572s
[INFO] 192.168.91.124:43375 - 29673 "A IN cnamemorepayload.dnstest.com. udp 46 false 512" NOERROR qr,aa,tc,rd,ra 7131 0.000742706s
[INFO] 192.168.91.124:55388 - 29673 "A IN cnamemorepayload.dnstest.com. tcp 46 false 65535" NOERROR qr,aa,rd,ra 7131 0.000774041s
[INFO] 192.168.91.124:55388 - 43245 "AAAA IN cnamemorepayload.dnstest.com. tcp 46 false 65535" NOERROR qr,aa,rd,ra 209 0.000032193s
[INFO] 192.168.91.124:39222 - 34173 "AAAA IN cnamemorepayload.dnstest.com. udp 46 false 512" NOERROR qr,aa,rd,ra 209 0.00004631s
[INFO] 192.168.91.124:39222 - 11127 "A IN cnamemorepayload.dnstest.com. udp 46 false 512" NOERROR qr,aa,tc,rd,ra 7131 0.000788196s
[INFO] 192.168.91.124:55390 - 11127 "A IN cnamemorepayload.dnstest.com. tcp 46 false 65535" NOERROR qr,aa,rd,ra 7131 0.000765893s
[INFO] 192.168.91.124:55390 - 34173 "AAAA IN cnamemorepayload.dnstest.com. tcp 46 false 65535" NOERROR qr,aa,rd,ra 209 0.000036576s
```
[morepayloadips.txt](https://github.com/coredns/coredns/files/6633892/morepayloadips.txt)

I suspect this heavy payload of IP's breaking something when only integrated with kubernetes service domains but not as a direct cname resolves.

In addition @chrisohaver could you remove/reduce cache in corefile or restart the coredns pod before testing, I believe caching changes the behavior, where the response is readily available for coredns to send out

**Comment by TheRealGoku** [comment]
In addition @chrisohaver could you remove/reduce cache in corefile or restart the coredns pod before testing, I believe caching changes the behavior, where the response is readily available for coredns to send out

**Comment by chrisohaver** [comment]
>> @TheRealGoku, In your tests, how large is the untruncated response for `morepayload`?

> The payload size in response is 55 bytes and just has cname in it

No, I mean the size of the `A` response - not the incomplete `CNAME` response.
When you query `morepayload.playwithtc.com`, how big is the _untruncated_ response.

> could you remove/reduce cache in corefile

I didn't use cache in my test.

**Comment by TheRealGoku** [comment]
got that

In [coredns-behavior-working.pcap](https://github.com/TheRealGoku/coredns-tc-behavior) - for `morepayload.playwithtc.com` query

The frame number 44 is the coredns response sent to client with TC flag - This response with no IP's and just cname in it, has payload size of `44` bytes.

Now after the client tcp follow up, the coredns tcp response with all `A` IPs over TCP packet has Payload size of `7606` bytes --> frame number 50.

**Comment by chrisohaver** [comment]
OK - thats _much_ bigger than 512 - I was testing with  a size of just over 512 ... I'll adjust my tests.

**Comment by chrisohaver** [comment]
ok - I made the `A` record response enormous (10000 bytes), and got expected behavior as with my other tests.  I got a truncated response (`CNAME` + `A` subset of records), with the TC bit set.

Although I cannot reproduce the result you see (with or without Kubernetes involved), I'll look into the inconsistent tc bit behavior I saw earlier - perhaps it's related.

> In addition, I performed a different test as you mentioned. The scenario follows where no kubernetes is involved

In your test, it looks like you created the CNAME in the upstream server - which only tests how coredns forwards a response. It doesn't really test how CoreDNS handles constructing a response from a CNAME. To test that, you can use the template plugins to create a CNAME... e.g.

```
  template IN A cname.test. {
    answer "cname.test. 60 IN CNAME morepayload.playwithtc.com."
  }
```

**Comment by TheRealGoku** [comment]
In your last test where you have used `10000` `A` records, is that at all loaded in coredns template plugin itself? or this `10000` records are loaded in an upstream server and being served via forward in coredns?

I agree with you on the fact that behavior could be different for constructing a dnsresponse based on template plugin vs forwarding response received from upstream. I suspect the problem arises only when forwarding response from upstream where upstream communication between coredns happened via tcp and tc flag set but when coredns is relaying that response to end client its not setting tc and just sending cname in it.

On the other hand you shouldn't see this issue happening(ideally) when coredns itself constructs response by checking template plugin where all data are readily available in hand to construct response.

I will load all the IP's in template plugin and will check

**Comment by chrisohaver** [comment]
> In your last test where you have used 10000 A records, is that at all loaded in coredns template plugin itself? or this 10000 records are loaded in an upstream server and being served via forward in coredns?

Thats 10000 bytes, not 10000 records.

Based on what you say later, I think you might be assuming otherwise, but they are located in an "upstream" server, served via forward. I used _hosts_ to define the `A` records in the "upstream" server for simplicity. I put "upstream" in quotes because the upstream server is actually coredns listening on a separate port for convenience.  But that's essentially the same thing as if it was a completely separate instance of coredns.

My (abbreviated) Corefile: 
```
.:5398 {
  hosts {
    1.0.0.0 cname.target.
    1.0.0.1 cname.target.

[ ... plus many many more records ...]

  }
}

.:5399 {
  template IN A cname.test. {
    answer "cname.test 60 IN CNAME cname.target."
  }
  kubernetes cluster.local {
    kubeconfig /Users/cohaver/.kube/config kind-kind
  }
  forward . 127.0.0.1:5398
}

```

**Comment by chrisohaver** [comment]
FYI, I believe I've discovered the root cause of the inconsistent TC bit I mentioned above.  In a nutshell, when we do an upstream lookup if that result was truncated, the answer to the client needs to have the tc bit set. It's an easy fix for _template_, less easy for backend users (_kubernetes_ and _etcd_), and kind of a horrible nightmare for _file_ and friends. The inconsistency stems from the whether to not the total response of CNAME + truncated A records exceeds the max length.  In some cases it will, in which case the response gets truncated, and marked truncated. In other cases it will not, in which case the response is not truncated, and not marked truncated (however the set of A records is in fact truncated).

 I'm working on a fix and should open a PR early next week.

**Comment by miekg** [comment]
if this is an internal query we could potentially query with a bigger buffer as 512 is unreasonable small.

otoh a cname target with 180 IPs assigned is a corner case - don't do that and expect things to work

**Comment by chrisohaver** [comment]
> otoh a cname target with 180 IPs assigned is a corner case - don't do that and expect things to work

@miekg, do you think it's not worth fixing? If so, I can close #4687.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] TC Flag not s..." ]
>    otoh a cname target with 180 IPs assigned is a corner case - don't do that
>    and expect things to work
>
***@***.***, do you think it's not worth fixing? If so, I can close #4687.

we might want to add a bigger buffer to external queries we initiate.. ?
But this corner case is not worth upsetting all code that uses this.

**Comment by chrisohaver** [comment]
upstream.Lookup currently uses the clients request size when making the request.
Using a really big buffer would reduce chance of an issue, but a response could always be bigger.

Perhaps we could make it always use TCP... then leave it to the writer to truncate.

**Comment by chrisohaver** [comment]
> Perhaps we could make it always use TCP... then leave it to the writer to truncate.

Nevermind that doesn't make sense.

**Comment by TheRealGoku** [comment]
180+ IP's that I have used is just for testing. This incident even occurred in acceptable range like 30 IP's with valid longer cname domain characters like what has been used in Elasticache cluster configuration endpoint such as `redis-goku.kldwqe.clustercfg.use1.cache.amazonaws.com` - the dns resolve for such domain name can have easily 30+ IP's when the node count grows / configured in combination with replica/shards. Considering the above example domain name character size, each A type resolved entry will be large.

**Comment by chrisohaver** [comment]
@TheRealGoku, another simpler workaround would be to add `force_tcp` to the _forward_ plugin (should work for the same reason node-local-dns works, the backend resolutions is done over tcp).

```
  forward . /etc/resolv.conf {
    force_tcp
  }
```

**Comment by chrisohaver** [comment]
> if this is an internal query we could potentially query with a bigger buffer as 512 is unreasonable small.

@miekg, Internal queries (i.e when CoreDNS is authoritative for the target name) won't get truncated since `upstream.Lookup` uses a non-writer. When the plugin serving the record writes, it won't scrub/truncate.
The issue occurs when the target is in a zone that CoreDNS is not authoritative for, and ends up sending lookups upstream through _forward_.  In this case, setting a large buffer could result in requests larger than desired in a user's setting (e.g. might result in udp packet fragmentation).  Currently `upstream.Lookup` uses the original request's protocol and buffer size when making the request, which I think is the correct behavior.

We could advise users to always set _forward_ to use `force_tcp` to avoid this issue, but doing so would force all forwarding to use TCP which might not be desirable.

IMO, it's best to fix the issue by persisting the TC bit to the client response.

**Comment by miekg** [comment]
hmm. I'll not that lib musl at some point (still does?) ignore the TC bit, so this doesn't add anything for that environment.

Also what problem (actual problem!) does this solve, the linked article talks about tc in general, If you have 180 targets after a cname you're abusing the dns for something it was clearly not meant to do.

**Comment by chrisohaver** [comment]
> If you have 180 targets after a cname you're abusing ...

I think that only stands if a large number of any single record type with the same name is considered abusive to DNS.

Nevertheless, the `upstream.Lookup` bug doesn't just affect `CNAME` target lookups.  It just so happens that `upstream.Lookup ` is most commonly used to lookup `CNAME` targets, but _dns64_ for example uses it in a different context.

Furthermore, a response could be truncated with a small number of targets if the target records are individually large, for example if the `CNAME` targets contains a large `TXT` record.
